# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [21]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [39]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [43]:
pd.__version__

'3.0.6'

In [40]:
chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

In [41]:
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [42]:
chipo.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

### Step 3. Name of the max valued product

In [23]:
# producto_comun = chipo["item_name"].value_counts().idxmax()
# print(producto_comun)

#MAL

Chicken Bowl

In [45]:
# Hay que calcular el precio unitario

chipo['item_price'] = pd.to_numeric(chipo['item_price'].astype(str).str.replace('$','', regex=False), errors='coerce') # quitar los dolares y convirtirlo a str

chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [48]:
# Pedido más caro
print(chipo.loc[chipo["item_price"].idxmax(), ["item_name", "item_price", "quantity"]])

#sacar el producto con el precio más alto, el producto, precio y cantidad

item_name     Chips and Fresh Tomato Salsa
item_price                           44.25
quantity                                15
Name: 3598, dtype: object

In [49]:
# calcular el precio unitario para saber el producto más caro por unidad
# creación de la variable 'unit_price'

chipo['unit_price']= chipo ['item_price']/ chipo ['quantity']
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price,unit_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98,10.98
6,3,1,Side of Chips,NaN,1.69,1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75,11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25,9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25,9.25

In [50]:
print(chipo.loc[chipo['unit_price'].idxmax(),['item_name','item_price','quantity', 'unit_price']])

item_name     Steak Salad Bowl
item_price               23.78
quantity                     2
unit_price               11.89
Name: 281, dtype: object

In [53]:
#más de un producto
productos_caros = chipo[chipo['unit_price'] == chipo['unit_price'].max()]
print(productos_caros['item_name'].unique())

<StringArray>
['Steak Salad Bowl', 'Carnitas Salad Bowl', 'Barbacoa Salad Bowl']
Length: 3, dtype: str

### Step 4. How many products cost more than $10.00?

In [24]:
#cantidad_productos = chipo["item_price"].str.replace("$", "").str.strip().astype(float) # Cambiar de str a float para poder utilizarlo como número
#(cantidad_productos > 10).sum()

np.int64(1130)

In [54]:
# Lista con los nombres sin repetir los productos que cuestan más 10
print(chipo.loc[chipo['unit_price']>10,'item_name'].unique())

#Número de elementos de la lista anterior
print(chipo.loc[chipo['unit_price'] > 10, 'item_name']. nunique())

<StringArray>
[         'Chicken Bowl',         'Steak Burrito',       'Chicken Burrito',
         'Barbacoa Bowl',        'Veggie Burrito',           'Veggie Bowl',
    'Chicken Soft Tacos',            'Steak Bowl',      'Carnitas Burrito',
         'Carnitas Bowl',      'Barbacoa Burrito',    'Chicken Salad Bowl',
 'Barbacoa Crispy Tacos',     'Veggie Salad Bowl',         'Chicken Salad',
      'Steak Salad Bowl',  'Chicken Crispy Tacos',     'Veggie Soft Tacos',
   'Barbacoa Soft Tacos', 'Carnitas Crispy Tacos',   'Carnitas Salad Bowl',
   'Barbacoa Salad Bowl',      'Steak Soft Tacos',   'Carnitas Soft Tacos',
    'Steak Crispy Tacos']
Length: 25, dtype: str
25

In [55]:
chipo[chipo['unit_price'] > 10.00][['item_name','item_price']]

               item_name  item_price
5           Chicken Bowl       10.98
7          Steak Burrito       11.75
13          Chicken Bowl       11.25
23       Chicken Burrito       10.98
39         Barbacoa Bowl       11.75
...                  ...         ...
4610       Steak Burrito       11.75
4611      Veggie Burrito       11.25
4617       Steak Burrito       11.75
4618       Steak Burrito       11.75
4619  Chicken Salad Bowl       11.25

[1034 rows x 2 columns]

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [25]:
#cantidad_pedidos = chipo.loc[cantidad_productos > 10, "order_id"].nunique()

#print(cantidad_pedidos)

# chipo.loc[cantidad_productos > 10, "order_id"] 
# loc permite seleccionar filas y columnas de un DataFrame.
# cantidad_productos > 10: selecciona las filas que cumplen la condición.
# "order_id": selecciona únicamente la columna que contiene los identificadores de los pedidos.
# nunique: Cuenta los valores únicos, es decir, los identificadores de pedido diferentes, sin contar repetidos.

863

In [57]:
print(chipo.loc[chipo["unit_price"] > 10, "order_id"].nunique())

787

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [59]:
cantidad_productos = chipo.groupby(chipo["order_id"])["item_price"].sum()
print(len(cantidad_productos > 10))

#Cuenta los pedidos que contienen más de 10 unidades de productos, independientemente de su precio.

1834

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [60]:
print(chipo.loc[(chipo['item_price']>10) & (chipo['quantity']>1),'order_id'].nunique())

117

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [61]:
chipo[["item_name", "unit_price"]]

                                  item_name  unit_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl        8.49
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [63]:
chipo.sort_values(by='item_name') 

# poner siempre by para estar seguro de que ordena siempre por la variable que se le pide

,order_id,quantity,item_name,choice_description,item_price,unit_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98,6.49
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49,6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49,6.49
...,...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75,8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [68]:
idx_implicito = chipo['item_price'].argmax() #argmax indice implicito, no puedes cambiar. Pides la fila
idx_explicito = chipo['item_price'].idxmax() # pides el indice explicito 

print(chipo.loc[idx_explicito, 'quantity']) 

#print(chipo.iloc[idx_implicito, 'quantity']) # posición de la fila en ese momento

print(chipo.loc[idx_explicito])
print(chipo.iloc[idx_implicito])

15
order_id                                      1443
quantity                                        15
item_name             Chips and Fresh Tomato Salsa
choice_description                             NaN
item_price                                   44.25
unit_price                                    2.95
Name: 3598, dtype: object
order_id                                      1443
quantity                                        15
item_name             Chips and Fresh Tomato Salsa
choice_description                             NaN
item_price                                   44.25
unit_price                                    2.95
Name: 3598, dtype: object

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [69]:
print((chipo['item_name']=="Veggie Salad Bowl").sum())

print(chipo.loc[chipo['item_name']== 'Veggie Salad Bowl', 'quantity'].sum())

18
18

### Step 9. How many times did someone order more than one Canned Soda?

In [70]:
print(chipo.loc[(chipo['item_name']== "Canned Soda") & (chipo['quantity']>1),"order_id"].nunique())

18